### ISSUE TITLE
image is set to "created" while actually failed

### ISSUE THREAD

**Issue by aparcar** [aparcar/attendedsysupgrade-server#146]
```
Feb 02 22:26:40 chef gunicorn3[15864]: ERROR:flask.app:Exception on /api/build-request/ad4d17a5256a [GET]
Feb 02 22:26:40 chef gunicorn3[15864]: Traceback (most recent call last):
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                                         
Feb 02 22:26:40 chef gunicorn3[15864]:     response = self.full_dispatch_request()
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                            
Feb 02 22:26:40 chef gunicorn3[15864]:     rv = self.handle_user_exception(e)
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                            
Feb 02 22:26:40 chef gunicorn3[15864]:     reraise(exc_type, exc_value, tb)
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise                                                                                                        
Feb 02 22:26:40 chef gunicorn3[15864]:     raise value
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                                                            
Feb 02 22:26:40 chef gunicorn3[15864]:     rv = self.dispatch_request()
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request                                                                                                 
Feb 02 22:26:40 chef gunicorn3[15864]:     return self.view_functions[rule.endpoint](**req.view_args)
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/server/asu/views.py", line 78, in api_files_request
Feb 02 22:26:40 chef gunicorn3[15864]:     return br.process_request(request_json)
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/server/asu/request.py", line 19, in process_request
Feb 02 22:26:40 chef gunicorn3[15864]:     return self._process_request()
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/server/asu/build_request.py", line 23, in _process_request
Feb 02 22:26:40 chef gunicorn3[15864]:     return self.return_status()
Feb 02 22:26:40 chef gunicorn3[15864]:   File "/home/aparcar/server/asu/build_request.py", line 134, in return_status
Feb 02 22:26:40 chef gunicorn3[15864]:     self.response_json["sysupgrade"] = "/download/{}/{}".format(image_path["file_path"], image_path["sysupgrade"])                                                                                     
Feb 02 22:26:40 chef gunicorn3[15864]: KeyError: 'file_path'

Need debugging to find the cause of an image_request being set to "created" while actually not entry is added to the "images" table

```

**Comment by aparcar** [comment]
fixed via https://github.com/aparcar/attendedsysupgrade-server/pull/149/commits/1aabeba55ffff7093b15a6d73805555fcca5dfe3#diff-c6f5c9fe5f95c085f15fb7a34029d0cfR117
